DIR_BUILD := ./dist
DIR_SRC := ./src

.PHONY: all
all: run

.PHONY: run
run:
	npm run dev

.PHONY: build
build:
	npm run build

.PHONY: update
update:
	npm update

.PHONY: clean
clean:
	rm -rf ${DIR_BUILD}
